# Makefile for MacOS X (Homebrew)
# Scott Tringali, 4/2026
#
# Homebrew X11 packages are keg-only and don't link into the main prefix,
# so each library needs its own path.

# Compatibility for nedit.rb
MOTIFLINK 	= -lXm

BREW_PREFIX     = /opt/homebrew
MOTIF_HOME      = $(BREW_PREFIX)/opt/openmotif
LIBXT_HOME      = $(BREW_PREFIX)/opt/libxt
LIBX11_HOME     = $(BREW_PREFIX)/opt/libx11
LIBXEXT_HOME    = $(BREW_PREFIX)/opt/libxext
LIBXPM_HOME     = $(BREW_PREFIX)/opt/libxpm
LIBSM_HOME      = $(BREW_PREFIX)/opt/libsm
LIBICE_HOME     = $(BREW_PREFIX)/opt/libice
LIBXP_HOME      = $(BREW_PREFIX)/opt/libxp

MACOS_INCLUDES  = -I$(BREW_PREFIX)/include
MACOS_LIBS      = -L$(MOTIF_HOME)/lib -L$(LIBXT_HOME)/lib \
                  -L$(LIBX11_HOME)/lib -L$(LIBXEXT_HOME)/lib \
                  -L$(LIBXPM_HOME)/lib -L$(LIBSM_HOME)/lib \
                  -L$(LIBICE_HOME)/lib -L$(LIBXP_HOME)/lib

############### You shouldn't need to edit anything below here ##############
CC=cc -std=c89
AR=libtool
ARFLAGS=-static -o

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
# To test if the Motif library exports the runtime version
# add -DHAVE__XMVERSIONSTRING to CFLAGS
#
CFLAGS=-O -DNO_XMIM -DUSE_DIRENT -DUSE_LPR_PRINT_CMD $(MACOS_INCLUDES)
LIBS=$(MACOS_LIBS) $(MOTIFLINK) -lXt -lX11

#
# generic part
#
include Makefile.common
