# Makefile for MacOS (MacPorts)
# Scott Tringali, 5/2026

PREFIX?=/opt/local

CC=cc -std=c89
AR=libtool
ARFLAGS=-static -o

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
# To test if the Motif library exports the runtime version
# add -DHAVE__XMVERSIONSTRING to CFLAGS
#
CFLAGS=-O -DNO_XMIM -DUSE_DIRENT -DUSE_LPR_PRINT_CMD -I$(PREFIX)/include
LIBS=-L$(PREFIX)/lib -lXm -lXt -lX11

#
# generic part
#
include Makefile.common
