# Makefile for OpenBSD (ports)
# Updated 5/2026: CC?/AR?, split LOCALBASE/X11BASE, updated libs
#
# Motif comes from ports (/usr/local), X11 from base (/usr/X11R6).
# Override LOCALBASE or X11BASE if your install differs.
#
LOCALBASE?=/usr/local
X11BASE?=/usr/X11R6

CC?=cc
AR?=ar
ARFLAGS=-ur

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
# To test if the Motif library exports the runtime version
# add -DHAVE__XMVERSIONSTRING to CFLAGS
#
CFLAGS=-O -I${X11BASE}/include -I${LOCALBASE}/include \
       -DUSE_DIRENT -DUSE_LPR_PRINT_CMD

MOTIFLIB?=-L${LOCALBASE}/lib -lXm
LIBS=${MOTIFLIB} -L${X11BASE}/lib -lXpm -lXext -lXt -lSM -lICE -lX11 -lm

include Makefile.common
