# Makefile for FreeBSD (ports)
# Updated 5/2026: fix PREFIX/MOTIFLIB, add ARFLAGS
#
# Requires ports: x11-toolkits/open-motif x11/libXpm
# Override PREFIX if your ports tree uses a non-standard prefix.
#
PREFIX?=/usr/local

CC?=cc
AR?=ar
ARFLAGS=-ur

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
# To test if the Motif library exports the runtime version
# add -DHAVE__XMVERSIONSTRING to CFLAGS
#
CFLAGS=-O -I${PREFIX}/include -DUSE_DIRENT -DUSE_LPR_PRINT_CMD -DUSE_XMIM
LIBS=-L${PREFIX}/lib -lXm -lXpm -lXext -lXt -lSM -lICE -lX11 -lm

include Makefile.common

install: nedit nc
	${INSTALL} ${COPY} ${STRIP} nedit $(DESTDIR)${PREFIX}/bin
	${INSTALL} ${COPY} ${STRIP} nc $(DESTDIR)${PREFIX}/bin/nclient
