name: Package
on:
  workflow_dispatch:

jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:stable-slim
    steps:
      - uses: actions/checkout@v4
      - name: Build source packages
        run: make dist
